apiVersion: v1
kind: Service
metadata:
  name: hppmodel1
spec:
  ports:
  - name: protobuf-api
    nodePort: 31581
    port: 31581
    targetPort: 8061
  selector:
    app: hppmodel1
  type: NodePort
