apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orchestrator
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - image: cicd.ai4eu-dev.eu:7444/generic-parallel-orchestrator/orchestrator_container:1.8
        imagePullPolicy: Always
        name: orchestrator
        ports:
        - containerPort: 8061
          name: mc-api
        - containerPort: 8062
          name: webui
